PUT http://localhost:3003/api/blogs/5a422a851b54a676234d17f7 HTTP/1.1
content-type: application/json

{
  "_id": "5a422a851b54a676234d17f7",
  "title": "UPDATED patterns",
  "author": "Michael Chan",
  "url": "https://updatedpatterns.com/",
  "likes": 666,
  "__v": 0
}