POST http://localhost:3003/api/blogs
content-type: application/json
Authorization: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpIiwiaWQiOiI1YzY2ZWY1OTFiMTg4MzViZDU1NzRmNmUiLCJpYXQiOjE1NTA1MjE4Njl9.SBj7-65iKmZPR3fwqUChQkO_7-UnqwNNn1DcQF-lAoA"

{
  "title": "React patterns",
  "author": "Michael Chan",
  "url": "https://reactpatterns.com/",
  "likes": 7
}